name: Bug Report
description: Заполните форму
title: "[BUG]: "
labels: ["bug"]

body:
  - type: dropdown
    id: critical
    attributes:
      label: Критическая ли ошибка?
      options:
        - Да
        - Нет
    validations:
      required: true

  - type: dropdown
    id: windows_version
    attributes:
      label: Выберите вашу систему Windows
      options:
        - Windows 10
        - Windows 11
    validations:
      required: true

  - type: input
    id: tab
    attributes:
      label: На какой вкладке произошел баг?
      placeholder: "Например: Проводник / Система и восстановление / Информация о ПК"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Опишите вашу проблему
      placeholder: Подробно опишите, что произошло
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Можно ли повторить? Шаги воспроизведения + скриншоты
      placeholder: |
        1. Перейти в ...
        2. Нажать на ...
        3. Увидеть ошибку
        
        Прикрепите скриншоты
    validations:
      required: true
